colorScheme = "marvel"
defaultAppearance = "dark"
autoSwitchAppearance = true
enableSearch = true
enableCodeCopy = true
mainSections = [ "projects" ]
defaultBackgroundImage = "img/anime-style-clouds.jpg"

[header]
layout = "fixed-fill-blur"
logo = "img/turtle.png"

[footer]
showCopyright = false
showThemeAttribution = false
showAppearanceSwitcher = true
showScrollToTop = true

[homepage]
layout = "card"
homepageImage = "img/test.jpg"
showRecent = false
showRecentItems = 3
showMoreLink = true
showMoreLinkDest = "/projects/"
cardView = true
cardViewScreenWidth = false
layoutBackgroundBlur = true

[article]
showDate = false
showDateUpdated = false
showAuthor = true
showHero = true
heroStyle = "background"
showBreadcrumbs = true
showDraftLabel = true
showEdit = false
editAppendPath = true
seriesOpened = false
showHeadingAnchors = true
showPagination = true
invertPagination = false
showReadingTime = false
showTableOfContents = true
showTaxonomies = false
showAuthorsBadges = false
showWordCount = false
showSummary = true
sharingLinks = [ "linkedin","email", "github" ,"scholar"]

[list]
showHero = true
heroStyle = "background"
layoutBackgroundHeaderSpace = false
showBreadcrumbs = false
showSummary = true
showTableOfContents = false
showCards = true
groupByYear = true
cardView = true
cardViewScreenWidth = false
layoutBackgroundBlur = false

[sitemap]
excludedKinds = []

[taxonomy]
showTermCount = true

[firebase]

[fathomAnalytics]

[verification]
